question_data = [
    {"type": "boolean",
     "difficulty": "medium",
     "question": "Seoul is the capital of North Korea.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean",
     "difficulty": "medium",
     "question": "Norway has a larger land area than Sweden.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean",
     "difficulty": "medium",
     "question": "The title of the 1969 film 'Krakatoa, East_of Java'; is incorrect, as Krakatoa is in fact west of Java.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean",
     "difficulty": "medium",
     "question": "Gothenburg is the capital of Sweden.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium",
     "question": "The surface area of Russia is slightly larger than that of the dwarf planet Pluto.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean",
     "difficulty": "medium",
     "question": "Is Tartu the capital of Estonia?",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean",
     "difficulty": "medium",
     "question": "Vietnam is the only country in the world that starts with V. ",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean",
     "difficulty": "medium",
     "question": "Israel is 7 hours ahead of New York.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean",
     "difficulty": "medium",
     "question": "Japan has left-hand side traffic.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean",
     "difficulty": "medium",
     "question": "The flag of South Africa features 7 colours.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean",
     "difficulty": "easy",
     "question": "New Haven is the capital city of the state of Connecticut in the United States.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean",
     "difficulty": "easy",
     "question": "San Marino is the only country completely surrounded by another country.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean",
     "difficulty": "easy",
     "question": "Nova Scotia is on the east coast of Canada.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean",
     "difficulty": "easy",
     "question": "Toronto is the capital city of the North American country of Canada.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean",
     "difficulty": "easy",
     "question": "There is a city called Rome in every continent on Earth.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean",
     "difficulty": "easy",
     "question": "California is larger than Japan.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean",
     "difficulty": "easy",
     "question": "Greenland is covered with grass and Iceland covered with ice.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean",
     "difficulty": "easy",
     "question": "Greenland is almost as big as Africa.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean",
     "difficulty": "easy",
     "question": "Tokyo is the capital of Japan.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean",
     "difficulty": "easy",
     "question": "Rhode Island is actually located on the US mainland, despite its name.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]}
]